#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         2
bspc config window_gap          5

bspc config top_padding 	0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#COMMANDS#
#sleep 10 is called for wait to pulseaudio module in polybar to be ready for use
#otherwise the module wont work, i dont know how to fix it and this is
#my temporal solution, if you know how can i fix it let me knowS
sleep 10
$HOME/.config/polybar/material/launch.sh
